services:
  libertyrustacquiring:
    container_name: libertyrustacquiring
    image: ${DOCKER_REGISTRY-}libertyrustacquiring
    build:
      context: .
      dockerfile: LibertyRustAcquiring/Dockerfile
    depends_on:
      - db
    networks:
      - appnet
  db:
    image: mariadb:latest
    environment:
      MYSQL_PASSWORD: iS56msYx30fgi4
      MYSQL_ROOT_PASSWORD: iS56msYx30fgi4
      MYSQL_DATABASE: libertyrustdb
      MYSQL_USER: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: iS56msYx30fgi4
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - appnet

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - appnet

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ihor.liberty@gmail.com -d payments.liberty-rp.com.ua --agree-tos
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge